apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev-test
  name: java-web-app-docker
  labels:
    app: java-web-app-docker
    version: latest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-web-app-docker
      version: latest
  template:
    metadata:
      name: java-web-app-docker
      labels:
        app: java-web-app-docker
        version: latest
    spec:
      containers: 
      - name: java-web-app-docker
        image: 44.192.24.140:8082/imageversion
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: nexus-login
---

apiVserion: v1
kind: Service
metadata:
  namespace: dev-test
  name: java-web-app-docker
  labels:
    app: java-web-app-docker
    version: latest 
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 32333
  selector:
    app: java-web-app-docker
    version: latest 
